GET https://localhost:7289/v1/Characters

###

GET https://localhost:7289/v1/Characters/02c07b82-1b85-8d01-17a3-ad6059be2a1c?$expand=Features,Effects

###

POST https://localhost:7289/v1/Characters
Content-Type: application/json

{
	"Id": "02c07b82-1b85-8d01-17a3-ad6059be2a1c",
	"Name": "Augustine Deckow",
	"Features": [
		{
			"Id": "333bad4f-b10d-4a30-971b-f449e4469952",
			"Name": "Dwarf"
		},
		{
			"Id": "7ec8239f-4e59-4b43-89f4-fb0ddb4557ac",
			"Name": "Elf"
		}
	],
	"Effects": []
}

###

PUT https://localhost:7289/v1/Characters
Content-Type: application/json

{
	"Id": "02c07b82-1b85-8d01-17a3-ad6059be2a1c",
	"Name": "Augustine Deckow",
	"Features": [
		{
		"Id": "333bad4f-b10d-4a30-971b-f449e4469952",
		"Name": "Dwarf",
		"Characters": [],
		"Effects": []
		},
		{
		"Id": "7ec8239f-4e59-4b43-89f4-fb0ddb4557ac",
		"Name": "Elf",
		"Characters": [],
		"Effects": []
		}
	],
	"Effects": [
		{
		"Id": "00000000-0000-0000-0000-000000000000",
		"Path": "/Strength",
		"Rule": "{\u0022\u002B\u0022: [{\u0022var\u0022: \u0022Strength\u0022}, 6]}",
		"CharacterId": "00000000-0000-0000-0000-000000000000"
		}
	]
}

###

PATCH https://localhost:7289/v1/Characters/02c07b82-1b85-8d01-17a3-ad6059be2a1c
Content-Type: application/json

{
	"Features": [
		{
			"Id": "333bad4f-b10d-4a30-971b-f449e4469952"
		}
	]
}
